import React from 'react';
import { 
    LayoutDashboard, 
    FolderKanban, 
    Users, 
    User,
    Wallet, 
    Calendar, 
    Package, 
    Users as UsersIcon, 
    Settings, 
    ChevronLeft, 
    ChevronRight,
    LogOut,
    Menu,
    X,
    Building,
    PlusCircle,
    Sun,
    Moon,
    ArrowUpRight,
    DollarSign,
    BarChart,
    PieChart,
    LineChart,
    UserCheck,
    Briefcase,
    FileText,
    Percent,
    ArrowDown,
    ArrowUp,
    AlertCircle,
    CheckCircle2,
    Search,
    LayoutGrid,
    List,
    Filter,
    Edit,
    Trash2,
    UploadCloud,
    Phone,
    RefreshCw,
    Activity,
    CreditCard,
    Paperclip
} from 'lucide-react';

export const Icons = {
    Dashboard: (props: React.SVGProps<SVGSVGElement>) => <LayoutDashboard {...props} />,
    Projects: (props: React.SVGProps<SVGSVGElement>) => <FolderKanban {...props} />,
    Customers: (props: React.SVGProps<SVGSVGElement>) => <Users {...props} />,
    Staff: (props: React.SVGProps<SVGSVGElement>) => <UserCheck {...props} />,
    Finance: (props: React.SVGProps<SVGSVGElement>) => <Wallet {...props} />,
    Calendar: (props: React.SVGProps<SVGSVGElement>) => <Calendar {...props} />,
    Packages: (props: React.SVGProps<SVGSVGElement>) => <Package {...props} />,
    Users: (props: React.SVGProps<SVGSVGElement>) => <UsersIcon {...props} />,
    Settings: (props: React.SVGProps<SVGSVGElement>) => <Settings {...props} />,
    Profile: (props: React.SVGProps<SVGSVGElement>) => <User {...props} />,
    ChevronLeft: (props: React.SVGProps<SVGSVGElement>) => <ChevronLeft {...props} />,
    ChevronRight: (props: React.SVGProps<SVGSVGElement>) => <ChevronRight {...props} />,
    Logout: (props: React.SVGProps<SVGSVGElement>) => <LogOut {...props} />,
    Menu: (props: React.SVGProps<SVGSVGElement>) => <Menu {...props} />,
    Close: (props: React.SVGProps<SVGSVGElement>) => <X {...props} />,
    Logo: (props: React.SVGProps<SVGSVGElement>) => <Building {...props} />,
    Add: (props: React.SVGProps<SVGSVGElement>) => <PlusCircle {...props} />,
    Sun: (props: React.SVGProps<SVGSVGElement>) => <Sun {...props} />,
    Moon: (props: React.SVGProps<SVGSVGElement>) => <Moon {...props} />,
    ArrowUpRight: (props: React.SVGProps<SVGSVGElement>) => <ArrowUpRight {...props} />,
    DollarSign: (props: React.SVGProps<SVGSVGElement>) => <DollarSign {...props} />,
    BarChart: (props: React.SVGProps<SVGSVGElement>) => <BarChart {...props} />,
    PieChart: (props: React.SVGProps<SVGSVGElement>) => <PieChart {...props} />,
    LineChart: (props: React.SVGProps<SVGSVGElement>) => <LineChart {...props} />,
    Briefcase: (props: React.SVGProps<SVGSVGElement>) => <Briefcase {...props} />,
    FileText: (props: React.SVGProps<SVGSVGElement>) => <FileText {...props} />,
    Percent: (props: React.SVGProps<SVGSVGElement>) => <Percent {...props} />,
    ArrowDown: (props: React.SVGProps<SVGSVGElement>) => <ArrowDown {...props} />,
    ArrowUp: (props: React.SVGProps<SVGSVGElement>) => <ArrowUp {...props} />,
    AlertCircle: (props: React.SVGProps<SVGSVGElement>) => <AlertCircle {...props} />,
    CheckCircle: (props: React.SVGProps<SVGSVGElement>) => <CheckCircle2 {...props} />,
    Search: (props: React.SVGProps<SVGSVGElement>) => <Search {...props} />,
    Grid: (props: React.SVGProps<SVGSVGElement>) => <LayoutGrid {...props} />,
    List: (props: React.SVGProps<SVGSVGElement>) => <List {...props} />,
    Filter: (props: React.SVGProps<SVGSVGElement>) => <Filter {...props} />,
    Edit: (props: React.SVGProps<SVGSVGElement>) => <Edit {...props} />,
    Trash: (props: React.SVGProps<SVGSVGElement>) => <Trash2 {...props} />,
    UploadCloud: (props: React.SVGProps<SVGSVGElement>) => <UploadCloud {...props} />,
    Phone: (props: React.SVGProps<SVGSVGElement>) => <Phone {...props} />,
    Sync: (props: React.SVGProps<SVGSVGElement>) => <RefreshCw {...props} />,
    Timeline: (props: React.SVGProps<SVGSVGElement>) => <Activity {...props} />,
    Payments: (props: React.SVGProps<SVGSVGElement>) => <CreditCard {...props} />,
    Files: (props: React.SVGProps<SVGSVGElement>) => <Paperclip {...props} />,
};

export type IconName = keyof typeof Icons;